<?php

namespace AppBundle\Entity\Grade;
use AppBundle\Model\Grade\GradeInterface;
use AppBundle\Model\Grade\GradeSessionGatewayInterface;
use AppBundle\Model\Grade\GradeSessionInterface;
use Doctrine\ORM\EntityRepository;

/**
 * GradeSessionGateway
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeSessionGateway extends EntityRepository implements GradeSessionGatewayInterface
{
    public function findNew(GradeInterface $grade, \DateTime $start_date = null, \DateTime $end_date = null)
    {
        return new GradeSession($grade, $start_date, $end_date);
    }

    public function insert(GradeSessionInterface $gradeSession)
    {
        $this->_em->persist($gradeSession);
        $this->_em->flush();

        return $gradeSession;

    }

    public function update()
    {
        // TODO: Implement update() method.
    }

    public function remove($id)
    {
        // TODO: Implement remove() method.
    }
}
