<?php

namespace AppBundle\Entity\Grade;
use AppBundle\Model\Grade\GradeInterface;
use AppBundle\Model\Grade\GradeSessionGatewayInterface;
use AppBundle\Model\Grade\GradeSessionInterface;
use Doctrine\ORM\EntityRepository;

/**
 * GradeSessionGateway
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeSessionGateway extends EntityRepository implements GradeSessionGatewayInterface
{
    /**
     * Get non-persisted object.
     *
     * @param GradeInterface $grade
     * @param \DateTime|null $start_date
     * @param \DateTime|null $end_date
     * @return GradeSession
     */
    public function findNew(GradeInterface $grade, \DateTime $start_date = null, \DateTime $end_date = null)
    {
        return new GradeSession($grade, $start_date, $end_date);
    }

    /**
     * Insert.
     *
     * @param GradeSessionInterface $gradeSession
     * @return GradeSessionInterface
     */
    public function insert(GradeSessionInterface $gradeSession)
    {
        $this->_em->persist($gradeSession);
        $this->_em->flush();

        return $gradeSession;

    }

    /**
     * Update.
     */
    public function update()
    {
        $this->_em->flush();
    }

    /**
     * Remove.
     *
     * @param $id
     */
    public function remove($id)
    {
        $grade = $this->find($id);
        $this->_em->remove($grade);
        $this->_em->flush();
    }
}
